### ISSUE TITLE
setting TLS version to 1.2 works for me

### ISSUE THREAD

**Issue by pat1** [maovidal/paho_sslpsk2_demo#3]
setting TLS version:
``` 
     context = SSLPSKContext(ssl.PROTOCOL_TLSv1_2)
```
it works! (for me) with sslpsk or sslpsk2

**Comment by maovidal** [comment]
Thank you for reporting that. You encouraged me to revisit this repo and make some changes.

Just to note that it should also work with `ssl.PROTOCOL_TLS_CLIENT` according to: 
https://docs.python.org/3/library/ssl.html?highlight=set_ciphers#ssl.PROTOCOL_TLS_CLIENT

I have updated the script.
